<a href="https://colab.research.google.com/github/srujannayak32/MLLAB189/blob/main/MLLAB.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
n = np.arange(15).reshape(5,3)
print(n)



[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [ ]:
n1 = np.arange(6).reshape(3,2)
print(n1)

[[0 1]
 [2 3]
 [4 5]]


In [ ]:
print(np.dot(n,n1))

[[ 10  13]
 [ 28  40]
 [ 46  67]
 [ 64  94]
 [ 82 121]]


In [ ]:
n=np.arange(11)
n2=(n[n%2 != 0])
print(n2)

[1 3 5 7 9]


In [ ]:
n=np.arange(10)
n[:]= np.mean(n)
print(n)

[4 4 4 4 4 4 4 4 4 4]


In [ ]:
n=np.ones((5,5))
print(n)
n[1:-1,1:-1] = 0
print(n)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [ ]:
n=np.array([1,2,3,4,5,6,7,3,4,2,9,22,4])
n2= np.unique(n,return_counts=True)
print(n2)

(array([ 1,  2,  3,  4,  5,  6,  7,  9, 22]), array([1, 2, 2, 3, 1, 1, 1, 1, 1]))


In [ ]:
n=np.random.random((3,3))
print(n)
n[n>0.5]=1
n[n<=0.5]=0
print(n)


[[0.08119809 0.85248017 0.63475618]
 [0.0981888  0.05261166 0.11971205]
 [0.66442912 0.32734523 0.78736779]]
[[0. 1. 1.]
 [0. 0. 0.]
 [1. 0. 1.]]


In [ ]:
import pandas as pd
df=pd.read_csv("/content/sample_data/mnist_test.csv")
print(df.shape)
print(type(df))
print(df.head())

(9999, 785)
<class 'pandas.core.frame.DataFrame'>
   7  0  0.1  0.2  0.3  0.4  0.5  0.6  0.7  0.8  ...  0.658  0.659  0.660  \
0  2  0    0    0    0    0    0    0    0    0  ...      0      0      0   
1  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   
2  0  0    0    0    0    0    0    0    0    0  ...      0      0      0   
3  4  0    0    0    0    0    0    0    0    0  ...      0      0      0   
4  1  0    0    0    0    0    0    0    0    0  ...      0      0      0   

   0.661  0.662  0.663  0.664  0.665  0.666  0.667  
0      0      0      0      0      0      0      0  
1      0      0      0      0      0      0      0  
2      0      0      0      0      0      0      0  
3      0      0      0      0      0      0      0  
4      0      0      0      0      0      0      0  

[5 rows x 785 columns]


In [ ]:
import sklearn as sk
from sklearn.datasets import load_iris

iris=load_iris()

print(iris.keys())
print(iris.data.shape)
print(iris.feature_names)
print(iris.DESCR)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
(150, 4)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
peta

In [ ]:
print(iris.data.shape[0])
print(df.isnull())
print(df.isna())

150
          7      0    0.1    0.2    0.3    0.4    0.5    0.6    0.7    0.8  \
0     False  False  False  False  False  False  False  False  False  False   
1     False  False  False  False  False  False  False  False  False  False   
2     False  False  False  False  False  False  False  False  False  False   
3     False  False  False  False  False  False  False  False  False  False   
4     False  False  False  False  False  False  False  False  False  False   
...     ...    ...    ...    ...    ...    ...    ...    ...    ...    ...   
9994  False  False  False  False  False  False  False  False  False  False   
9995  False  False  False  False  False  False  False  False  False  False   
9996  False  False  False  False  False  False  False  False  False  False   
9997  False  False  False  False  False  False  False  False  False  False   
9998  False  False  False  False  False  False  False  False  False  False   

      ...  0.658  0.659  0.660  0.661  0.662  0.663  0.664 

In [ ]:
import numpy as np
#n=np.array([1,-2,-54,3,-53,12,-32,90,-87])
n1=np.arange(9).reshape(3,3)
normalized_matrix=(n1-np.mean(n1))/np.std(n1)
print(normalized_matrix)

[[-1.54919334 -1.161895   -0.77459667]
 [-0.38729833  0.          0.38729833]
 [ 0.77459667  1.161895    1.54919334]]


In [ ]:
n1[::-1]

array([[6, 7, 8],
       [3, 4, 5],
       [0, 1, 2]])

In [ ]:
n=np.arange(12).reshape(4,3)
print(np.vstack((n,n1)))

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]]


In [ ]:
print(np.intersect1d(n,n1))

[0 1 2 3 4 5 6 7 8]


In [ ]:
n2=np.random.randint(0,3,10)
print(n2)

[2 2 1 0 0 1 2 2 0 1]


In [ ]:
print(n)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [ ]:
n3=np.mean(n,axis=1)
print(n3)

[ 1.  4.  7. 10.]


In [ ]:
n4=np.arange(33)
n4[:]=np.mean(n4)
print(n4)

[16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16 16
 16 16 16 16 16 16 16 16 16]


In [ ]:
import pandas as pd
from sklearn.datasets import load_iris

iris=load_iris()
df=pd.DataFrame(iris.data,columns=iris.feature_names)
df['Id'] = range(1, len(df) + 1)
print(df.head())
df = df.drop('Id', axis=1)
print(df.head())

   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)  \
0                5.1               3.5                1.4               0.2   
1                4.9               3.0                1.4               0.2   
2                4.7               3.2                1.3               0.2   
3                4.6               3.1                1.5               0.2   
4                5.0               3.6                1.4               0.2   

   Id  
0   1  
1   2  
2   3  
3   4  
4   5  
   sepal length (cm)  sepal width (cm)  petal length (cm)  petal width (cm)
0                5.1               3.5                1.4               0.2
1                4.9               3.0                1.4               0.2
2                4.7               3.2                1.3               0.2
3                4.6               3.1                1.5               0.2
4                5.0               3.6                1.4               0.2


WEEK-2 PRACTICE


In [1]:
import sklearn as sk
import pandas as pd
from sklearn.datasets import load_iris

iris=load_iris()
df=pd.DataFrame(iris.data)
print(df)
print(df.shape)
print(type(df))
print(df.dtypes)
print(df.head(3))

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]
(150, 4)
<class 'pandas.core.frame.DataFrame'>
0    float64
1    float64
2    float64
3    float64
dtype: object
     0    1    2    3
0  5.1  3.5  1.4  0.2
1  4.9  3.0  1.4  0.2
2  4.7  3.2  1.3  0.2


In [2]:
import sklearn as sk
import pandas as pd
from sklearn.datasets import load_iris

iris=load_iris()
df=pd.DataFrame(iris.data)
print(df)
missing_values = df.isnull().sum()
display(missing_values)

       0    1    2    3
0    5.1  3.5  1.4  0.2
1    4.9  3.0  1.4  0.2
2    4.7  3.2  1.3  0.2
3    4.6  3.1  1.5  0.2
4    5.0  3.6  1.4  0.2
..   ...  ...  ...  ...
145  6.7  3.0  5.2  2.3
146  6.3  2.5  5.0  1.9
147  6.5  3.0  5.2  2.0
148  6.2  3.4  5.4  2.3
149  5.9  3.0  5.1  1.8

[150 rows x 4 columns]


0    0
1    0
2    0
3    0
dtype: int64

In [3]:
import sklearn
import numpy as np
from sklearn import datasets
iris = datasets.load_iris()
print(iris.keys())
print(iris.data.shape)
print(iris.feature_names)
print(iris.DESCR)
print("no.of observations: ", iris.data.shape[0])
missingvals = np.isnan(iris.data).sum()
print("no.of missing values: ", missingvals)

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])
(150, 4)
['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']
.. _iris_dataset:

Iris plants dataset
--------------------

**Data Set Characteristics:**

:Number of Instances: 150 (50 in each of three classes)
:Number of Attributes: 4 numeric, predictive attributes and the class
:Attribute Information:
    - sepal length in cm
    - sepal width in cm
    - petal length in cm
    - petal width in cm
    - class:
            - Iris-Setosa
            - Iris-Versicolour
            - Iris-Virginica

:Summary Statistics:

============== ==== ==== ======= ===== ====================
                Min  Max   Mean    SD   Class Correlation
============== ==== ==== ======= ===== ====================
sepal length:   4.3  7.9   5.84   0.83    0.7826
sepal width:    2.0  4.4   3.05   0.43   -0.4194
petal length:   1.0  6.9   3.76   1.76    0.9490  (high!)
peta